title: Thao Trang Nguyen
logo: /assets/img/headshot_circle.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  With five years in economics, policy and data science, I am dedicated to applying my knowledge of Economics and Causal Inference to address challenging business problems. I am passionate about fostering innovation, encouraging teamwork, and ensuring a focus on the customer.
  <br><br>
  <a href="https://www.linkedin.com/in/trangnguyen177/">View my LinkedIn Profile</a> 
theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
